// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package example

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	chi "github.com/go-chi/chi/v5"
	validation "github.com/go-ozzo/ozzo-validation/v4"
	cast "github.com/spf13/cast"
	"io"
	"net/http"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
)

var xFingerprintRegex = regexp.MustCompile("[0-9a-fA-F]+")

// Hooks are observability callbacks fired by the generated routing layer.
// Any field may be left nil — ensureHooks() at handler-init time fills the
// nil entries with no-op stubs, so call sites never need to nil-check.
//
// Contract: hooks are for observability (logging, metrics, tracing). The
// runtime owns the response. ResponseBodyMarshalFailed receives an
// http.ResponseWriter for inspection only — the runtime calls http.Error
// immediately after the hook returns, so writing to w from the hook will
// produce a duplicate-WriteHeader warning. Read headers/r.Context() at most.
type Hooks struct {
	RequestSecurityParseFailed    func(*http.Request, string, RequestProcessingResult)
	RequestSecurityParseCompleted func(*http.Request, string)
	RequestSecurityCheckFailed    func(*http.Request, string, string, RequestProcessingResult)
	RequestSecurityCheckCompleted func(*http.Request, string, string)
	RequestBodyUnmarshalFailed    func(*http.Request, string, RequestProcessingResult)
	RequestHeaderParseFailed      func(*http.Request, string, string, RequestProcessingResult)
	RequestPathParseFailed        func(*http.Request, string, string, RequestProcessingResult)
	RequestQueryParseFailed       func(*http.Request, string, string, RequestProcessingResult)
	RequestBodyValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestHeaderValidationFailed func(*http.Request, string, RequestProcessingResult)
	RequestPathValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestQueryValidationFailed  func(*http.Request, string, RequestProcessingResult)
	RequestBodyUnmarshalCompleted func(*http.Request, string)
	RequestHeaderParseCompleted   func(*http.Request, string)
	RequestPathParseCompleted     func(*http.Request, string)
	RequestQueryParseCompleted    func(*http.Request, string)
	RequestParseCompleted         func(*http.Request, string)
	RequestProcessingCompleted    func(*http.Request, string)
	RequestRedirectStarted        func(*http.Request, string, string)
	ResponseBodyMarshalCompleted  func(*http.Request, string)
	ResponseBodyWriteCompleted    func(*http.Request, string, int)
	ResponseBodyMarshalFailed     func(http.ResponseWriter, *http.Request, string, error)
	ResponseBodyWriteFailed       func(*http.Request, string, int, error)
	ServiceCompleted              func(*http.Request, string)
}

func ensureHooks(h *Hooks) *Hooks {
	if h == nil {
		h = &Hooks{}
	}
	if h.RequestSecurityParseFailed == nil {
		h.RequestSecurityParseFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityParseCompleted == nil {
		h.RequestSecurityParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestSecurityCheckFailed == nil {
		h.RequestSecurityCheckFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityCheckCompleted == nil {
		h.RequestSecurityCheckCompleted = func(*http.Request, string, string) {}
	}
	if h.RequestBodyUnmarshalFailed == nil {
		h.RequestBodyUnmarshalFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderParseFailed == nil {
		h.RequestHeaderParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestPathParseFailed == nil {
		h.RequestPathParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestQueryParseFailed == nil {
		h.RequestQueryParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestBodyValidationFailed == nil {
		h.RequestBodyValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderValidationFailed == nil {
		h.RequestHeaderValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestPathValidationFailed == nil {
		h.RequestPathValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestQueryValidationFailed == nil {
		h.RequestQueryValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestBodyUnmarshalCompleted == nil {
		h.RequestBodyUnmarshalCompleted = func(*http.Request, string) {}
	}
	if h.RequestHeaderParseCompleted == nil {
		h.RequestHeaderParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestPathParseCompleted == nil {
		h.RequestPathParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestQueryParseCompleted == nil {
		h.RequestQueryParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestParseCompleted == nil {
		h.RequestParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestProcessingCompleted == nil {
		h.RequestProcessingCompleted = func(*http.Request, string) {}
	}
	if h.RequestRedirectStarted == nil {
		h.RequestRedirectStarted = func(*http.Request, string, string) {}
	}
	if h.ResponseBodyMarshalCompleted == nil {
		h.ResponseBodyMarshalCompleted = func(*http.Request, string) {}
	}
	if h.ResponseBodyWriteCompleted == nil {
		h.ResponseBodyWriteCompleted = func(*http.Request, string, int) {}
	}
	if h.ResponseBodyMarshalFailed == nil {
		h.ResponseBodyMarshalFailed = func(http.ResponseWriter, *http.Request, string, error) {}
	}
	if h.ResponseBodyWriteFailed == nil {
		h.ResponseBodyWriteFailed = func(*http.Request, string, int, error) {}
	}
	if h.ServiceCompleted == nil {
		h.ServiceCompleted = func(*http.Request, string) {}
	}
	return h
}

func extractSecurity(
	r *http.Request,
	hooks *Hooks,
	name string,
	requirements [][]securityProcessor,
	skipCheck bool,
) (results map[SecurityScheme]string, passed bool, checkErr error) {
	if skipCheck {
		// Expose every extractable credential across all OR-branches so the
		// handler can decide. Validation is skipped by contract.
		for _, processors := range requirements {
			for _, processor := range processors {
				_, value, isExtracted := processor.extract(r)
				if !isExtracted {
					continue
				}
				if results == nil {
					results = map[SecurityScheme]string{}
				}
				results[processor.scheme] = value
			}
		}
		return results, true, nil
	}

	for _, processors := range requirements {
		// Per-branch buffer: a partially-extracted branch must not leak its
		// credentials into the final results.
		branchResults := map[SecurityScheme]string{}
		linkedChecksValid := true
		attemptCheckErr := error(nil)
		for _, processor := range processors {
			schemeName, value, isExtracted := processor.extract(r)
			if !isExtracted {
				linkedChecksValid = false
				break
			}
			if err := processor.handle(r, processor.scheme, schemeName, value); err != nil {
				hooks.RequestSecurityCheckFailed(r, name, string(processor.scheme),
					RequestProcessingResult{error: err, typee: SecurityCheckFailed})
				linkedChecksValid = false
				attemptCheckErr = err
				break
			}
			hooks.RequestSecurityCheckCompleted(r, name, string(processor.scheme))
			branchResults[processor.scheme] = value
		}
		if linkedChecksValid {
			if len(branchResults) > 0 {
				results = branchResults
			}
			return results, true, nil
		}
		// Preserve the first real handle() error across OR-branches. A later
		// branch that fails only on extract (attemptCheckErr stays nil) must
		// NOT overwrite a real auth-handler error from an earlier branch.
		if checkErr == nil {
			checkErr = attemptCheckErr
		}
	}
	return results, false, checkErr
}

type requestProcessingResultType uint8

const (
	ParseSucceed requestProcessingResultType = iota
	BodyUnmarshalFailed
	BodyValidationFailed
	HeaderParseFailed
	HeaderValidationFailed
	QueryParseFailed
	QueryValidationFailed
	PathParseFailed
	PathValidationFailed
	SecurityParseFailed
	SecurityCheckFailed
)

type RequestProcessingResult struct {
	error error
	typee requestProcessingResultType
}

func NewRequestProcessingResult(t requestProcessingResultType, err error) RequestProcessingResult {
	return RequestProcessingResult{
		error: err,
		typee: t,
	}
}

func (r RequestProcessingResult) Type() requestProcessingResultType {
	return r.typee
}

func (r RequestProcessingResult) Err() error {
	return r.error
}

var (
	_ = reflect.ValueOf
)

func isNilResponse(v responseInterface) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Pointer, reflect.Interface, reflect.Chan, reflect.Func, reflect.Map, reflect.Slice:
		return rv.IsNil()
	}
	return false
}

func AuthHandler(impl AuthService, r chi.Router, hooks *Hooks, securitySchemas SecuritySchemas) http.Handler {
	hooks = ensureHooks(hooks)

	router := &authRouter{router: r, service: impl, hooks: hooks}

	router.securityHandlers = map[SecurityScheme]securityProcessor{
		SecuritySchemeApiKeyAuth: {
			scheme:  SecuritySchemeApiKeyAuth,
			extract: securityExtractorsFuncs[SecuritySchemeApiKeyAuth],
			handle:  securitySchemas.SecuritySchemeApiKeyAuth,
		},
		SecuritySchemeBearer: {
			scheme:  SecuritySchemeBearer,
			extract: securityExtractorsFuncs[SecuritySchemeBearer],
			handle:  securitySchemas.SecuritySchemeBearer,
		},
	}

	router.postBearerEndpointSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeBearer]}}

	router.getSecureEndpointSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeApiKeyAuth]}}

	router.getSemiSecureEndpointSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeApiKeyAuth]}}

	router.mount()

	return router.router
}

type authRouter struct {
	router                            chi.Router
	service                           AuthService
	hooks                             *Hooks
	securityHandlers                  map[SecurityScheme]securityProcessor
	postBearerEndpointSecurityReqs    [][]securityProcessor
	getSecureEndpointSecurityReqs     [][]securityProcessor
	getSemiSecureEndpointSecurityReqs [][]securityProcessor
}

func (router *authRouter) mount() {
	router.router.Post("/bearer-endpoint", router.PostBearerEndpoint)
	router.router.Get("/secure-endpoint", router.GetSecureEndpoint)
	router.router.Get("/semi-secure-endpoint", router.GetSemiSecureEndpoint)
}

func (router *authRouter) parsePostBearerEndpointRequest(r *http.Request) (request PostBearerEndpointRequest) {

	results, passed, checkErr := extractSecurity(r, router.hooks, "PostBearerEndpoint", router.postBearerEndpointSecurityReqs, false)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "PostBearerEndpoint", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "PostBearerEndpoint")

	router.hooks.RequestParseCompleted(r, "PostBearerEndpoint")

	return
}

func (router *authRouter) PostBearerEndpoint(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PostBearerEndpoint(r.Context(), router.parsePostBearerEndpointRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "PostBearerEndpoint", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "PostBearerEndpoint", result.inner(), true)
}

func (router *authRouter) parseGetSecureEndpointRequest(r *http.Request) (request GetSecureEndpointRequest) {

	results, passed, checkErr := extractSecurity(r, router.hooks, "GetSecureEndpoint", router.getSecureEndpointSecurityReqs, false)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "GetSecureEndpoint", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "GetSecureEndpoint")

	router.hooks.RequestParseCompleted(r, "GetSecureEndpoint")

	return
}

func (router *authRouter) GetSecureEndpoint(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetSecureEndpoint(r.Context(), router.parseGetSecureEndpointRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "GetSecureEndpoint", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "GetSecureEndpoint", result.inner(), true)
}

func (router *authRouter) parseGetSemiSecureEndpointRequest(r *http.Request) (request GetSemiSecureEndpointRequest) {

	results, passed, checkErr := extractSecurity(r, router.hooks, "GetSemiSecureEndpoint", router.getSemiSecureEndpointSecurityReqs, true)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "GetSemiSecureEndpoint", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "GetSemiSecureEndpoint")

	router.hooks.RequestParseCompleted(r, "GetSemiSecureEndpoint")

	return
}

func (router *authRouter) GetSemiSecureEndpoint(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetSemiSecureEndpoint(r.Context(), router.parseGetSemiSecureEndpointRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "GetSemiSecureEndpoint", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "GetSemiSecureEndpoint", result.inner(), true)
}

func CallbacksHandler(impl CallbacksService, r chi.Router, hooks *Hooks, securitySchemas SecuritySchemas) http.Handler {
	hooks = ensureHooks(hooks)

	router := &callbacksRouter{router: r, service: impl, hooks: hooks}

	router.securityHandlers = map[SecurityScheme]securityProcessor{
		SecuritySchemeCookie: {
			scheme:  SecuritySchemeCookie,
			extract: securityExtractorsFuncs[SecuritySchemeCookie],
			handle:  securitySchemas.SecuritySchemeCookie,
		},
	}

	router.postCallbacksCallbackTypeSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeCookie]}}

	router.mount()

	return router.router
}

type callbacksRouter struct {
	router                                chi.Router
	service                               CallbacksService
	hooks                                 *Hooks
	securityHandlers                      map[SecurityScheme]securityProcessor
	postCallbacksCallbackTypeSecurityReqs [][]securityProcessor
}

func (router *callbacksRouter) mount() {
	router.router.Post("/callbacks/{callbackType}", router.PostCallbacksCallbackType)
}

func (router *callbacksRouter) parsePostCallbacksCallbackTypeRequest(r *http.Request) (request PostCallbacksCallbackTypeRequest) {
	query := r.URL.Query()

	results, passed, checkErr := extractSecurity(r, router.hooks, "PostCallbacksCallbackType", router.postCallbacksCallbackTypeSecurityReqs, false)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "PostCallbacksCallbackType", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "PostCallbacksCallbackType")

	pathCallbackType := chi.URLParam(r, "callbackType")
	if pathCallbackType == "" {
		err := errCallbackTypeIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathParseFailed}
		router.hooks.RequestPathParseFailed(r, "PostCallbacksCallbackType", "callbackType", request.ProcessingResult)

		return
	}

	request.Path.CallbackType = pathCallbackType

	if err := request.Path.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathValidationFailed}
		router.hooks.RequestPathValidationFailed(r, "PostCallbacksCallbackType", request.ProcessingResult)

		return
	}

	router.hooks.RequestPathParseCompleted(r, "PostCallbacksCallbackType")

	queryHasSmthStr := query.Get("hasSmth")
	if queryHasSmthStr != "" {
		queryHasSmth, err := strconv.ParseBool(queryHasSmthStr)
		if err != nil {
			request.ProcessingResult = RequestProcessingResult{error: err, typee: QueryParseFailed}
			router.hooks.RequestQueryParseFailed(r, "PostCallbacksCallbackType", "hasSmth", request.ProcessingResult)

			return
		}

		request.Query.HasSmth = queryHasSmth
	}

	if err := request.Query.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: QueryValidationFailed}
		router.hooks.RequestQueryValidationFailed(r, "PostCallbacksCallbackType", request.ProcessingResult)

		return
	}

	router.hooks.RequestQueryParseCompleted(r, "PostCallbacksCallbackType")

	var (
		body      RawPayload
		decodeErr error
	)
	bodyBytes, readErr := io.ReadAll(r.Body)
	if readErr != nil {
		decodeErr = readErr
	} else {
		body = RawPayload(bodyBytes)
	}
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		router.hooks.RequestBodyUnmarshalFailed(r, "PostCallbacksCallbackType", request.ProcessingResult)

		return
	}

	request.Body = body

	router.hooks.RequestBodyUnmarshalCompleted(r, "PostCallbacksCallbackType")

	router.hooks.RequestParseCompleted(r, "PostCallbacksCallbackType")

	return
}

func (router *callbacksRouter) PostCallbacksCallbackType(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PostCallbacksCallbackType(r.Context(), router.parsePostCallbacksCallbackTypeRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "PostCallbacksCallbackType", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "PostCallbacksCallbackType", result.inner(), true)
}

func TransactionsHandler(impl TransactionsService, r chi.Router, hooks *Hooks, securitySchemas SecuritySchemas) http.Handler {
	hooks = ensureHooks(hooks)

	router := &transactionsRouter{router: r, service: impl, hooks: hooks}

	router.securityHandlers = map[SecurityScheme]securityProcessor{
		SecuritySchemeBearer: {
			scheme:  SecuritySchemeBearer,
			extract: securityExtractorsFuncs[SecuritySchemeBearer],
			handle:  securitySchemas.SecuritySchemeBearer,
		},
		SecuritySchemeCookie: {
			scheme:  SecuritySchemeCookie,
			extract: securityExtractorsFuncs[SecuritySchemeCookie],
			handle:  securitySchemas.SecuritySchemeCookie,
		},
	}

	router.deleteTransactionsUUIDSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeBearer]}, {router.securityHandlers[SecuritySchemeCookie]}}

	router.mount()

	return router.router
}

type transactionsRouter struct {
	router                             chi.Router
	service                            TransactionsService
	hooks                              *Hooks
	securityHandlers                   map[SecurityScheme]securityProcessor
	deleteTransactionsUUIDSecurityReqs [][]securityProcessor
}

func (router *transactionsRouter) mount() {
	router.router.Post("/transaction", router.PostTransaction)
	router.router.Put("/transaction", router.PutTransaction)
	router.router.Delete("/transactions/{uuid}", router.DeleteTransactionsUUID)
}

func (router *transactionsRouter) parsePostTransactionRequest(r *http.Request) (request PostTransactionRequest) {
	headerXSignature := r.Header.Get("x-signature")
	request.Header.XSignature = headerXSignature

	headerXFingerprint := r.Header.Get("x-fingerprint")
	if headerXFingerprint == "" {
		err := errXFingerprintIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "PostTransaction", "x-fingerprint", request.ProcessingResult)

		return
	}

	if !xFingerprintRegex.MatchString(headerXFingerprint) {
		err := errXFingerprintNotMatchedByThe09aFAFRegex

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "PostTransaction", "x-fingerprint", request.ProcessingResult)

		return
	}

	request.Header.XFingerprint = headerXFingerprint

	if err := request.Header.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderValidationFailed}
		router.hooks.RequestHeaderValidationFailed(r, "PostTransaction", request.ProcessingResult)

		return
	}

	router.hooks.RequestHeaderParseCompleted(r, "PostTransaction")

	var (
		body      CreateTransactionRequest
		decodeErr error
	)
	decodeErr = json.NewDecoder(r.Body).Decode(&body)
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		router.hooks.RequestBodyUnmarshalFailed(r, "PostTransaction", request.ProcessingResult)

		return
	}

	request.Body = body

	router.hooks.RequestBodyUnmarshalCompleted(r, "PostTransaction")

	if err := request.Body.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: BodyValidationFailed}
		router.hooks.RequestBodyValidationFailed(r, "PostTransaction", request.ProcessingResult)

		return
	}

	router.hooks.RequestParseCompleted(r, "PostTransaction")

	return
}

func (router *transactionsRouter) PostTransaction(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PostTransaction(r.Context(), router.parsePostTransactionRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "PostTransaction", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "PostTransaction", result.inner(), true)
}

func (router *transactionsRouter) parsePutTransactionRequest(r *http.Request) (request PutTransactionRequest) {
	headerXSignature := r.Header.Get("x-signature")
	request.Header.XSignature = headerXSignature

	headerXFingerprint := r.Header.Get("x-fingerprint")
	if headerXFingerprint == "" {
		err := errXFingerprintIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "PutTransaction", "x-fingerprint", request.ProcessingResult)

		return
	}

	if !xFingerprintRegex.MatchString(headerXFingerprint) {
		err := errXFingerprintNotMatchedByThe09aFAFRegex

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "PutTransaction", "x-fingerprint", request.ProcessingResult)

		return
	}

	request.Header.XFingerprint = headerXFingerprint

	if err := request.Header.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderValidationFailed}
		router.hooks.RequestHeaderValidationFailed(r, "PutTransaction", request.ProcessingResult)

		return
	}

	router.hooks.RequestHeaderParseCompleted(r, "PutTransaction")

	var (
		body      UpdateTransactionRequest
		decodeErr error
	)
	decodeErr = json.NewDecoder(r.Body).Decode(&body)
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		router.hooks.RequestBodyUnmarshalFailed(r, "PutTransaction", request.ProcessingResult)

		return
	}

	request.Body = body

	router.hooks.RequestBodyUnmarshalCompleted(r, "PutTransaction")

	router.hooks.RequestParseCompleted(r, "PutTransaction")

	return
}

func (router *transactionsRouter) PutTransaction(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PutTransaction(r.Context(), router.parsePutTransactionRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "PutTransaction", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "PutTransaction", result.inner(), true)
}

func (router *transactionsRouter) parseDeleteTransactionsUUIDRequest(r *http.Request) (request DeleteTransactionsUUIDRequest) {
	query := r.URL.Query()

	results, passed, checkErr := extractSecurity(r, router.hooks, "DeleteTransactionsUUID", router.deleteTransactionsUUIDSecurityReqs, false)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "DeleteTransactionsUUID", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "DeleteTransactionsUUID")

	headerXSignature := r.Header.Get("x-signature")
	request.Header.XSignature = headerXSignature

	headerXFingerprint := r.Header.Get("x-fingerprint")
	if headerXFingerprint == "" {
		err := errXFingerprintIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "DeleteTransactionsUUID", "x-fingerprint", request.ProcessingResult)

		return
	}

	if !xFingerprintRegex.MatchString(headerXFingerprint) {
		err := errXFingerprintNotMatchedByThe09aFAFRegex

		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderParseFailed}
		router.hooks.RequestHeaderParseFailed(r, "DeleteTransactionsUUID", "x-fingerprint", request.ProcessingResult)

		return
	}

	request.Header.XFingerprint = headerXFingerprint

	if err := request.Header.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: HeaderValidationFailed}
		router.hooks.RequestHeaderValidationFailed(r, "DeleteTransactionsUUID", request.ProcessingResult)

		return
	}

	router.hooks.RequestHeaderParseCompleted(r, "DeleteTransactionsUUID")

	pathUUID := chi.URLParam(r, "uuid")
	if pathUUID == "" {
		err := errUUIDIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathParseFailed}
		router.hooks.RequestPathParseFailed(r, "DeleteTransactionsUUID", "uuid", request.ProcessingResult)

		return
	}

	request.Path.UUID = pathUUID

	pathRegexParam := chi.URLParam(r, "regexParam")
	if pathRegexParam == "" {
		err := errRegexParamIsEmpty

		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathParseFailed}
		router.hooks.RequestPathParseFailed(r, "DeleteTransactionsUUID", "regexParam", request.ProcessingResult)

		return
	}

	if !regexParamRegex.MatchString(pathRegexParam) {
		err := errRegexParamNotMatchedByTheDRegex

		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathParseFailed}
		router.hooks.RequestPathParseFailed(r, "DeleteTransactionsUUID", "regexParam", request.ProcessingResult)

		return
	}

	request.Path.RegexParam = pathRegexParam

	if err := request.Path.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: PathValidationFailed}
		router.hooks.RequestPathValidationFailed(r, "DeleteTransactionsUUID", request.ProcessingResult)

		return
	}

	router.hooks.RequestPathParseCompleted(r, "DeleteTransactionsUUID")

	queryTimeParamStr := query.Get("timeParam")
	if queryTimeParamStr != "" {
		queryTimeParam, err := cast.ToTimeE(queryTimeParamStr)
		if err != nil {
			request.ProcessingResult = RequestProcessingResult{error: err, typee: QueryParseFailed}
			router.hooks.RequestQueryParseFailed(r, "DeleteTransactionsUUID", "timeParam", request.ProcessingResult)

			return
		}

		request.Query.TimeParam = queryTimeParam
	}

	if err := request.Query.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: QueryValidationFailed}
		router.hooks.RequestQueryValidationFailed(r, "DeleteTransactionsUUID", request.ProcessingResult)

		return
	}

	router.hooks.RequestQueryParseCompleted(r, "DeleteTransactionsUUID")

	router.hooks.RequestParseCompleted(r, "DeleteTransactionsUUID")

	return
}

func (router *transactionsRouter) DeleteTransactionsUUID(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.DeleteTransactionsUUID(r.Context(), router.parseDeleteTransactionsUUIDRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "DeleteTransactionsUUID", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "DeleteTransactionsUUID", result.inner(), true)
}

type response struct {
	statusCode  int
	body        interface{}
	bodyRaw     []byte
	contentType string
	redirectURL string
	headers     map[string]string
	cookies     []http.Cookie
}

type responseInterface interface {
	inner() *response
}

var (
	_ = xml.Marshal
	_ = json.Marshal
	_ = errors.New
	_ = fmt.Sprint
	_ = reflect.ValueOf
)

func respond(w http.ResponseWriter, r *http.Request, hooks *Hooks, name string, resp *response, hasContent bool) {
	for header, value := range resp.headers {
		w.Header().Set(header, value)
	}

	cookies := resp.cookies
	for i := range cookies {
		http.SetCookie(w, &cookies[i])
	}

	if url := resp.redirectURL; url != "" {
		switch resp.statusCode {
		case 301, 302, 303, 307, 308:
			hooks.RequestRedirectStarted(r, name, url)
			http.Redirect(w, r, url, resp.statusCode)
			hooks.ServiceCompleted(r, name)
			return
		}
	}

	hooks.RequestProcessingCompleted(r, name)

	if !hasContent {
		w.WriteHeader(resp.statusCode)
		hooks.ServiceCompleted(r, name)
		return
	}

	// Marshal BEFORE writing the status code so a serialization failure can
	// still surface as a clean 500 instead of a 2xx with a truncated body —
	// once WriteHeader fires, headers/status are committed to the wire and
	// we can no longer signal the error to the client.
	var body []byte
	if resp.body != nil {
		var err error
		switch resp.contentType {
		case "application/xml":
			body, err = xml.Marshal(resp.body)
		case "application/octet-stream":
			// Fast path for []byte and its aliases (e.g. type X = []byte).
			// Fall back to reflect for named types whose underlying type is
			// []byte (type X []byte) — the plain type assertion above would
			// fail those since Go checks type identity, not underlying type.
			if b, ok := (resp.body).([]byte); ok {
				body = b
			} else {
				rv := reflect.ValueOf(resp.body)
				if rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8 {
					body = rv.Bytes()
				} else {
					err = errors.New("body is not []byte")
				}
			}
		case "text/html":
			body = []byte(fmt.Sprint(resp.body))
		case "application/json":
			fallthrough
		default:
			body, err = json.Marshal(resp.body)
		}
		if err != nil {
			hooks.ResponseBodyMarshalFailed(w, r, name, err)
			http.Error(w, "internal server error", http.StatusInternalServerError)
			return
		}
		hooks.ResponseBodyMarshalCompleted(r, name)
	} else if len(resp.bodyRaw) > 0 {
		body = resp.bodyRaw
	}

	if ct := resp.contentType; ct != "" {
		w.Header().Set("Content-Type", ct)
	}
	w.WriteHeader(resp.statusCode)

	if len(body) > 0 {
		count, err := w.Write(body)
		if err != nil {
			hooks.ResponseBodyWriteFailed(r, name, count, err)
			return
		}
		hooks.ResponseBodyWriteCompleted(r, name, count)
	}

	hooks.ServiceCompleted(r, name)
}

type PostBearerEndpointResponse interface {
	responseInterface
	postBearerEndpointResponse()
}

type postBearerEndpointResponse struct {
	response
}

func (*postBearerEndpointResponse) postBearerEndpointResponse() {}

func (r *postBearerEndpointResponse) inner() *response {
	return &r.response
}

type PostCallbacksCallbackTypeResponse interface {
	responseInterface
	postCallbacksCallbackTypeResponse()
}

type postCallbacksCallbackTypeResponse struct {
	response
}

func (*postCallbacksCallbackTypeResponse) postCallbacksCallbackTypeResponse() {}

func (r *postCallbacksCallbackTypeResponse) inner() *response {
	return &r.response
}

type GetSecureEndpointResponse interface {
	responseInterface
	getSecureEndpointResponse()
}

type getSecureEndpointResponse struct {
	response
}

func (*getSecureEndpointResponse) getSecureEndpointResponse() {}

func (r *getSecureEndpointResponse) inner() *response {
	return &r.response
}

type GetSemiSecureEndpointResponse interface {
	responseInterface
	getSemiSecureEndpointResponse()
}

type getSemiSecureEndpointResponse struct {
	response
}

func (*getSemiSecureEndpointResponse) getSemiSecureEndpointResponse() {}

func (r *getSemiSecureEndpointResponse) inner() *response {
	return &r.response
}

type PostTransactionResponse interface {
	responseInterface
	postTransactionResponse()
}

type postTransactionResponse struct {
	response
}

func (*postTransactionResponse) postTransactionResponse() {}

func (r *postTransactionResponse) inner() *response {
	return &r.response
}

type PutTransactionResponse interface {
	responseInterface
	putTransactionResponse()
}

type putTransactionResponse struct {
	response
}

func (*putTransactionResponse) putTransactionResponse() {}

func (r *putTransactionResponse) inner() *response {
	return &r.response
}

type DeleteTransactionsUUIDResponse interface {
	responseInterface
	deleteTransactionsUUIDResponse()
}

type deleteTransactionsUUIDResponse struct {
	response
}

func (*deleteTransactionsUUIDResponse) deleteTransactionsUUIDResponse() {}

func (r *deleteTransactionsUUIDResponse) inner() *response {
	return &r.response
}

type postBearerEndpointStatusCodeResponseBuilder struct {
	response
}

func PostBearerEndpointResponseBuilder() *postBearerEndpointStatusCodeResponseBuilder {
	return new(postBearerEndpointStatusCodeResponseBuilder)
}

func (builder *postBearerEndpointStatusCodeResponseBuilder) StatusCode200() *postBearerEndpoint200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &postBearerEndpoint200ContentTypeBuilder{response: builder.response}
}

type postBearerEndpoint200ContentTypeBuilder struct {
	response
}

type PostBearerEndpoint200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostBearerEndpoint200ApplicationJsonResponseBuilder) Build() PostBearerEndpointResponse {
	return &postBearerEndpointResponse{response: builder.response}
}

func (builder *postBearerEndpoint200ContentTypeBuilder) ApplicationJson() *postBearerEndpoint200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postBearerEndpoint200ApplicationJsonBodyBuilder{response: builder.response}
}

type postBearerEndpoint200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postBearerEndpoint200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostBearerEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostBearerEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postBearerEndpoint200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostBearerEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostBearerEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postBearerEndpoint200ApplicationJsonBodyBuilder) Body(body PostBearerEndpoint200ApplicationJson) *PostBearerEndpoint200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostBearerEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postBearerEndpointStatusCodeResponseBuilder) StatusCode401() *PostBearerEndpoint401ResponseBuilder {
	builder.response.statusCode = 401

	return &PostBearerEndpoint401ResponseBuilder{response: builder.response}
}

type PostBearerEndpoint401ResponseBuilder struct {
	response
}

func (builder *PostBearerEndpoint401ResponseBuilder) Build() PostBearerEndpointResponse {
	return &postBearerEndpointResponse{response: builder.response}
}

type postCallbacksCallbackTypeStatusCodeResponseBuilder struct {
	response
}

func PostCallbacksCallbackTypeResponseBuilder() *postCallbacksCallbackTypeStatusCodeResponseBuilder {
	return new(postCallbacksCallbackTypeStatusCodeResponseBuilder)
}

func (builder *postCallbacksCallbackTypeStatusCodeResponseBuilder) StatusCode200() *postCallbacksCallbackType200HeadersBuilder {
	builder.response.statusCode = 200

	return &postCallbacksCallbackType200HeadersBuilder{response: builder.response}
}

type PostCallbacksCallbackType200Headers struct {
	XJwsSignature string
}

func (headers PostCallbacksCallbackType200Headers) toMap() map[string]string {
	return map[string]string{"x-jws-signature": cast.ToString(headers.XJwsSignature)}
}

type postCallbacksCallbackType200HeadersBuilder struct {
	response
}

func (builder *postCallbacksCallbackType200HeadersBuilder) Headers(headers PostCallbacksCallbackType200Headers) *postCallbacksCallbackType200CookiesBuilder {
	builder.headers = headers.toMap()

	return &postCallbacksCallbackType200CookiesBuilder{response: builder.response}
}

type postCallbacksCallbackType200CookiesBuilder struct {
	response
}

func (builder *postCallbacksCallbackType200CookiesBuilder) SetCookie(cookie ...http.Cookie) *postCallbacksCallbackType200ContentTypeBuilder {
	builder.cookies = cookie
	return &postCallbacksCallbackType200ContentTypeBuilder{response: builder.response}
}

type postCallbacksCallbackType200ContentTypeBuilder struct {
	response
}

type PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder struct {
	response
}

func (builder *PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder) Build() PostCallbacksCallbackTypeResponse {
	return &postCallbacksCallbackTypeResponse{response: builder.response}
}

func (builder *postCallbacksCallbackType200ContentTypeBuilder) ApplicationOctetStream() *postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder {
	builder.response.contentType = "application/octet-stream"

	return &postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder{response: builder.response}
}

type postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder struct {
	response
}

func (builder *postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder{response: builder.response}
}

func (builder *postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder) BodyBytes(body []byte) *PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder {
	builder.response.bodyRaw = body

	return &PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder{response: builder.response}
}

func (builder *postCallbacksCallbackType200ApplicationOctetStreamBodyBuilder) Body(body RawPayload) *PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder {
	builder.response.body = body

	return &PostCallbacksCallbackType200ApplicationOctetStreamResponseBuilder{response: builder.response}
}

func (builder *postCallbacksCallbackTypeStatusCodeResponseBuilder) StatusCode307(redirectURL string) *postCallbacksCallbackType307HeadersBuilder {
	builder.response.statusCode = 307
	builder.response.redirectURL = redirectURL

	return &postCallbacksCallbackType307HeadersBuilder{response: builder.response}
}

type PostCallbacksCallbackType307Headers struct {
	ReferrerPolicy string
}

func (headers PostCallbacksCallbackType307Headers) toMap() map[string]string {
	return map[string]string{"Referrer-Policy": cast.ToString(headers.ReferrerPolicy)}
}

type postCallbacksCallbackType307HeadersBuilder struct {
	response
}

func (builder *postCallbacksCallbackType307HeadersBuilder) Headers(headers PostCallbacksCallbackType307Headers) *PostCallbacksCallbackType307ResponseBuilder {
	builder.headers = headers.toMap()

	return &PostCallbacksCallbackType307ResponseBuilder{response: builder.response}
}

type PostCallbacksCallbackType307ResponseBuilder struct {
	response
}

func (builder *PostCallbacksCallbackType307ResponseBuilder) Build() PostCallbacksCallbackTypeResponse {
	return &postCallbacksCallbackTypeResponse{response: builder.response}
}

type getSecureEndpointStatusCodeResponseBuilder struct {
	response
}

func GetSecureEndpointResponseBuilder() *getSecureEndpointStatusCodeResponseBuilder {
	return new(getSecureEndpointStatusCodeResponseBuilder)
}

func (builder *getSecureEndpointStatusCodeResponseBuilder) StatusCode200() *getSecureEndpoint200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &getSecureEndpoint200ContentTypeBuilder{response: builder.response}
}

type getSecureEndpoint200ContentTypeBuilder struct {
	response
}

type GetSecureEndpoint200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *GetSecureEndpoint200ApplicationJsonResponseBuilder) Build() GetSecureEndpointResponse {
	return &getSecureEndpointResponse{response: builder.response}
}

func (builder *getSecureEndpoint200ContentTypeBuilder) ApplicationJson() *getSecureEndpoint200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &getSecureEndpoint200ApplicationJsonBodyBuilder{response: builder.response}
}

type getSecureEndpoint200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *getSecureEndpoint200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *GetSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &GetSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSecureEndpoint200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *GetSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &GetSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSecureEndpoint200ApplicationJsonBodyBuilder) Body(body GetSecureEndpoint200ApplicationJson) *GetSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &GetSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSecureEndpointStatusCodeResponseBuilder) StatusCode401() *GetSecureEndpoint401ResponseBuilder {
	builder.response.statusCode = 401

	return &GetSecureEndpoint401ResponseBuilder{response: builder.response}
}

type GetSecureEndpoint401ResponseBuilder struct {
	response
}

func (builder *GetSecureEndpoint401ResponseBuilder) Build() GetSecureEndpointResponse {
	return &getSecureEndpointResponse{response: builder.response}
}

type getSemiSecureEndpointStatusCodeResponseBuilder struct {
	response
}

func GetSemiSecureEndpointResponseBuilder() *getSemiSecureEndpointStatusCodeResponseBuilder {
	return new(getSemiSecureEndpointStatusCodeResponseBuilder)
}

func (builder *getSemiSecureEndpointStatusCodeResponseBuilder) StatusCode200() *getSemiSecureEndpoint200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &getSemiSecureEndpoint200ContentTypeBuilder{response: builder.response}
}

type getSemiSecureEndpoint200ContentTypeBuilder struct {
	response
}

type GetSemiSecureEndpoint200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *GetSemiSecureEndpoint200ApplicationJsonResponseBuilder) Build() GetSemiSecureEndpointResponse {
	return &getSemiSecureEndpointResponse{response: builder.response}
}

func (builder *getSemiSecureEndpoint200ContentTypeBuilder) ApplicationJson() *getSemiSecureEndpoint200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &getSemiSecureEndpoint200ApplicationJsonBodyBuilder{response: builder.response}
}

type getSemiSecureEndpoint200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *getSemiSecureEndpoint200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *GetSemiSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &GetSemiSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSemiSecureEndpoint200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *GetSemiSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &GetSemiSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSemiSecureEndpoint200ApplicationJsonBodyBuilder) Body(body GetSemiSecureEndpoint200ApplicationJson) *GetSemiSecureEndpoint200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &GetSemiSecureEndpoint200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getSemiSecureEndpointStatusCodeResponseBuilder) StatusCode400() *GetSemiSecureEndpoint400ResponseBuilder {
	builder.response.statusCode = 400

	return &GetSemiSecureEndpoint400ResponseBuilder{response: builder.response}
}

type GetSemiSecureEndpoint400ResponseBuilder struct {
	response
}

func (builder *GetSemiSecureEndpoint400ResponseBuilder) Build() GetSemiSecureEndpointResponse {
	return &getSemiSecureEndpointResponse{response: builder.response}
}

type postTransactionStatusCodeResponseBuilder struct {
	response
}

func PostTransactionResponseBuilder() *postTransactionStatusCodeResponseBuilder {
	return new(postTransactionStatusCodeResponseBuilder)
}

func (builder *postTransactionStatusCodeResponseBuilder) StatusCode201() *postTransaction201ContentTypeBuilder {
	builder.response.statusCode = 201

	return &postTransaction201ContentTypeBuilder{response: builder.response}
}

type postTransaction201ContentTypeBuilder struct {
	response
}

type PostTransaction201ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostTransaction201ApplicationJsonResponseBuilder) Build() PostTransactionResponse {
	return &postTransactionResponse{response: builder.response}
}

func (builder *postTransaction201ContentTypeBuilder) ApplicationJson() *postTransaction201ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postTransaction201ApplicationJsonBodyBuilder{response: builder.response}
}

type postTransaction201ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postTransaction201ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostTransaction201ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostTransaction201ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction201ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostTransaction201ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostTransaction201ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction201ApplicationJsonBodyBuilder) Body(body GenericResponse) *PostTransaction201ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostTransaction201ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransactionStatusCodeResponseBuilder) StatusCode400() *postTransaction400ContentTypeBuilder {
	builder.response.statusCode = 400

	return &postTransaction400ContentTypeBuilder{response: builder.response}
}

type postTransaction400ContentTypeBuilder struct {
	response
}

type PostTransaction400ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostTransaction400ApplicationJsonResponseBuilder) Build() PostTransactionResponse {
	return &postTransactionResponse{response: builder.response}
}

func (builder *postTransaction400ContentTypeBuilder) ApplicationJson() *postTransaction400ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postTransaction400ApplicationJsonBodyBuilder{response: builder.response}
}

type postTransaction400ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postTransaction400ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostTransaction400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction400ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostTransaction400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction400ApplicationJsonBodyBuilder) Body(body GenericResponse) *PostTransaction400ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransactionStatusCodeResponseBuilder) StatusCode500() *postTransaction500ContentTypeBuilder {
	builder.response.statusCode = 500

	return &postTransaction500ContentTypeBuilder{response: builder.response}
}

type postTransaction500ContentTypeBuilder struct {
	response
}

type PostTransaction500ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostTransaction500ApplicationJsonResponseBuilder) Build() PostTransactionResponse {
	return &postTransactionResponse{response: builder.response}
}

func (builder *postTransaction500ContentTypeBuilder) ApplicationJson() *postTransaction500ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postTransaction500ApplicationJsonBodyBuilder{response: builder.response}
}

type postTransaction500ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postTransaction500ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostTransaction500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction500ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostTransaction500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postTransaction500ApplicationJsonBodyBuilder) Body(body GenericResponse) *PostTransaction500ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

type putTransactionStatusCodeResponseBuilder struct {
	response
}

func PutTransactionResponseBuilder() *putTransactionStatusCodeResponseBuilder {
	return new(putTransactionStatusCodeResponseBuilder)
}

func (builder *putTransactionStatusCodeResponseBuilder) StatusCode200() *putTransaction200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &putTransaction200ContentTypeBuilder{response: builder.response}
}

type putTransaction200ContentTypeBuilder struct {
	response
}

type PutTransaction200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PutTransaction200ApplicationJsonResponseBuilder) Build() PutTransactionResponse {
	return &putTransactionResponse{response: builder.response}
}

func (builder *putTransaction200ContentTypeBuilder) ApplicationJson() *putTransaction200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &putTransaction200ApplicationJsonBodyBuilder{response: builder.response}
}

type putTransaction200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *putTransaction200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PutTransaction200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PutTransaction200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PutTransaction200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PutTransaction200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction200ApplicationJsonBodyBuilder) Body(body GenericResponse) *PutTransaction200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PutTransaction200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransactionStatusCodeResponseBuilder) StatusCode400() *putTransaction400ContentTypeBuilder {
	builder.response.statusCode = 400

	return &putTransaction400ContentTypeBuilder{response: builder.response}
}

type putTransaction400ContentTypeBuilder struct {
	response
}

type PutTransaction400ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PutTransaction400ApplicationJsonResponseBuilder) Build() PutTransactionResponse {
	return &putTransactionResponse{response: builder.response}
}

func (builder *putTransaction400ContentTypeBuilder) ApplicationJson() *putTransaction400ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &putTransaction400ApplicationJsonBodyBuilder{response: builder.response}
}

type putTransaction400ApplicationJsonBodyBuilder struct {
	response
}

func (builder *putTransaction400ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PutTransaction400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PutTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction400ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PutTransaction400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PutTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction400ApplicationJsonBodyBuilder) Body(body GenericResponse) *PutTransaction400ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PutTransaction400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransactionStatusCodeResponseBuilder) StatusCode500() *putTransaction500ContentTypeBuilder {
	builder.response.statusCode = 500

	return &putTransaction500ContentTypeBuilder{response: builder.response}
}

type putTransaction500ContentTypeBuilder struct {
	response
}

type PutTransaction500ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PutTransaction500ApplicationJsonResponseBuilder) Build() PutTransactionResponse {
	return &putTransactionResponse{response: builder.response}
}

func (builder *putTransaction500ContentTypeBuilder) ApplicationJson() *putTransaction500ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &putTransaction500ApplicationJsonBodyBuilder{response: builder.response}
}

type putTransaction500ApplicationJsonBodyBuilder struct {
	response
}

func (builder *putTransaction500ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PutTransaction500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PutTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction500ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PutTransaction500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PutTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *putTransaction500ApplicationJsonBodyBuilder) Body(body GenericResponse) *PutTransaction500ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PutTransaction500ApplicationJsonResponseBuilder{response: builder.response}
}

type deleteTransactionsUUIDStatusCodeResponseBuilder struct {
	response
}

func DeleteTransactionsUUIDResponseBuilder() *deleteTransactionsUUIDStatusCodeResponseBuilder {
	return new(deleteTransactionsUUIDStatusCodeResponseBuilder)
}

func (builder *deleteTransactionsUUIDStatusCodeResponseBuilder) StatusCode200() *deleteTransactionsUUID200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &deleteTransactionsUUID200ContentTypeBuilder{response: builder.response}
}

type deleteTransactionsUUID200ContentTypeBuilder struct {
	response
}

type DeleteTransactionsUUID200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *DeleteTransactionsUUID200ApplicationJsonResponseBuilder) Build() DeleteTransactionsUUIDResponse {
	return &deleteTransactionsUUIDResponse{response: builder.response}
}

func (builder *deleteTransactionsUUID200ContentTypeBuilder) ApplicationJson() *deleteTransactionsUUID200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &deleteTransactionsUUID200ApplicationJsonBodyBuilder{response: builder.response}
}

type deleteTransactionsUUID200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *deleteTransactionsUUID200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *DeleteTransactionsUUID200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &DeleteTransactionsUUID200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *deleteTransactionsUUID200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *DeleteTransactionsUUID200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &DeleteTransactionsUUID200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *deleteTransactionsUUID200ApplicationJsonBodyBuilder) Body(body GenericResponse) *DeleteTransactionsUUID200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &DeleteTransactionsUUID200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *deleteTransactionsUUIDStatusCodeResponseBuilder) StatusCode400() *deleteTransactionsUUID400ContentTypeBuilder {
	builder.response.statusCode = 400

	return &deleteTransactionsUUID400ContentTypeBuilder{response: builder.response}
}

type deleteTransactionsUUID400ContentTypeBuilder struct {
	response
}

type DeleteTransactionsUUID400ApplicationJsonResponseBuilder struct {
	response
}

func (builder *DeleteTransactionsUUID400ApplicationJsonResponseBuilder) Build() DeleteTransactionsUUIDResponse {
	return &deleteTransactionsUUIDResponse{response: builder.response}
}

func (builder *deleteTransactionsUUID400ContentTypeBuilder) ApplicationJson() *deleteTransactionsUUID400ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &deleteTransactionsUUID400ApplicationJsonBodyBuilder{response: builder.response}
}

type deleteTransactionsUUID400ApplicationJsonBodyBuilder struct {
	response
}

func (builder *deleteTransactionsUUID400ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *DeleteTransactionsUUID400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &DeleteTransactionsUUID400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *deleteTransactionsUUID400ApplicationJsonBodyBuilder) BodyBytes(body []byte) *DeleteTransactionsUUID400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &DeleteTransactionsUUID400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *deleteTransactionsUUID400ApplicationJsonBodyBuilder) Body(body GenericResponse) *DeleteTransactionsUUID400ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &DeleteTransactionsUUID400ApplicationJsonResponseBuilder{response: builder.response}
}

type AuthService interface {
	PostBearerEndpoint(context.Context, PostBearerEndpointRequest) PostBearerEndpointResponse
	GetSecureEndpoint(context.Context, GetSecureEndpointRequest) GetSecureEndpointResponse
	GetSemiSecureEndpoint(context.Context, GetSemiSecureEndpointRequest) GetSemiSecureEndpointResponse
}

type CallbacksService interface {
	PostCallbacksCallbackType(context.Context, PostCallbacksCallbackTypeRequest) PostCallbacksCallbackTypeResponse
}

type TransactionsService interface {
	PostTransaction(context.Context, PostTransactionRequest) PostTransactionResponse
	PutTransaction(context.Context, PutTransactionRequest) PutTransactionResponse
	DeleteTransactionsUUID(context.Context, DeleteTransactionsUUIDRequest) DeleteTransactionsUUIDResponse
}

type PostBearerEndpointRequest struct {
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

type GetSecureEndpointRequest struct {
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

type GetSemiSecureEndpointRequest struct {
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

type PostCallbacksCallbackTypeRequestPath struct {
	CallbackType string
}

func (path PostCallbacksCallbackTypeRequestPath) GetCallbackType() string {
	return path.CallbackType
}

func (path PostCallbacksCallbackTypeRequestPath) Validate() error {
	return nil
}

type PostCallbacksCallbackTypeRequestQuery struct {
	HasSmth bool
}

func (query PostCallbacksCallbackTypeRequestQuery) GetHasSmth() bool {
	return query.HasSmth
}

func (query PostCallbacksCallbackTypeRequestQuery) Validate() error {
	return nil
}

type PostCallbacksCallbackTypeRequest struct {
	Body                 RawPayload
	Path                 PostCallbacksCallbackTypeRequestPath
	Query                PostCallbacksCallbackTypeRequestQuery
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

type PostTransactionRequestHeader struct {
	XFingerprint string `json:"x-fingerprint"`
	XSignature   string `json:"x-signature"`
}

func (header PostTransactionRequestHeader) GetXFingerprint() string {
	return header.XFingerprint
}

func (header PostTransactionRequestHeader) GetXSignature() string {
	return header.XSignature
}

func (header PostTransactionRequestHeader) Validate() error {
	return validation.ValidateStruct(&header,
		validation.Field(&header.XFingerprint, validation.Required, validation.RuneLength(32, 32), validation.Match(xFingerprintRegex)),
		validation.Field(&header.XSignature, validation.Skip.When(header.XSignature == ""), validation.RuneLength(0, 5)))
}

type PostTransactionRequest struct {
	Body             CreateTransactionRequest
	Header           PostTransactionRequestHeader
	ProcessingResult RequestProcessingResult
}

type PutTransactionRequestHeader struct {
	XFingerprint string `json:"x-fingerprint"`
	XSignature   string `json:"x-signature"`
}

func (header PutTransactionRequestHeader) GetXFingerprint() string {
	return header.XFingerprint
}

func (header PutTransactionRequestHeader) GetXSignature() string {
	return header.XSignature
}

func (header PutTransactionRequestHeader) Validate() error {
	return validation.ValidateStruct(&header,
		validation.Field(&header.XFingerprint, validation.Required, validation.RuneLength(32, 32), validation.Match(xFingerprintRegex)),
		validation.Field(&header.XSignature, validation.Skip.When(header.XSignature == ""), validation.RuneLength(0, 5)))
}

type PutTransactionRequest struct {
	Body             UpdateTransactionRequest
	Header           PutTransactionRequestHeader
	ProcessingResult RequestProcessingResult
}

type DeleteTransactionsUUIDRequestHeader struct {
	XFingerprint string `json:"x-fingerprint"`
	XSignature   string `json:"x-signature"`
}

func (header DeleteTransactionsUUIDRequestHeader) GetXFingerprint() string {
	return header.XFingerprint
}

func (header DeleteTransactionsUUIDRequestHeader) GetXSignature() string {
	return header.XSignature
}

func (header DeleteTransactionsUUIDRequestHeader) Validate() error {
	return validation.ValidateStruct(&header,
		validation.Field(&header.XFingerprint, validation.Required, validation.RuneLength(32, 32), validation.Match(xFingerprintRegex)),
		validation.Field(&header.XSignature, validation.Skip.When(header.XSignature == ""), validation.RuneLength(0, 5)))
}

type DeleteTransactionsUUIDRequestPath struct {
	RegexParam string
	UUID       string
}

func (path DeleteTransactionsUUIDRequestPath) GetRegexParam() string {
	return path.RegexParam
}

func (path DeleteTransactionsUUIDRequestPath) GetUUID() string {
	return path.UUID
}

func (path DeleteTransactionsUUIDRequestPath) Validate() error {
	return validation.ValidateStruct(&path,
		validation.Field(&path.RegexParam, validation.Required, validation.RuneLength(5, 0), validation.Match(regexParamRegex)))
}

type DeleteTransactionsUUIDRequestQuery struct {
	TimeParam time.Time
}

func (query DeleteTransactionsUUIDRequestQuery) GetTimeParam() time.Time {
	return query.TimeParam
}

func (query DeleteTransactionsUUIDRequestQuery) Validate() error {
	return nil
}

type DeleteTransactionsUUIDRequest struct {
	Header               DeleteTransactionsUUIDRequestHeader
	Path                 DeleteTransactionsUUIDRequestPath
	Query                DeleteTransactionsUUIDRequestQuery
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

type SecurityScheme string

const (
	SecuritySchemeApiKeyAuth SecurityScheme = "ApiKeyAuth"
	SecuritySchemeBasic      SecurityScheme = "Basic"
	SecuritySchemeBearer     SecurityScheme = "Bearer"
	SecuritySchemeCookie     SecurityScheme = "Cookie"
)

type securityProcessor struct {
	scheme  SecurityScheme
	extract func(r *http.Request) (string, string, bool)
	handle  func(r *http.Request, scheme SecurityScheme, name string, value string) error
}

var securityExtractorsFuncs = map[SecurityScheme]func(r *http.Request) (string, string, bool){
	SecuritySchemeApiKeyAuth: func(r *http.Request) (string, string, bool) {
		value := r.Header.Get("X-API-Key")

		return "X-API-Key", value, value != ""
	},
	SecuritySchemeBasic: func(r *http.Request) (string, string, bool) {
		value := r.Header.Get("Authorization")

		if !strings.HasPrefix(value, "Bearer ") {
			return "", "", false
		}

		value = value[7:]

		return "Authorization", value, value != ""
	},
	SecuritySchemeBearer: func(r *http.Request) (string, string, bool) {
		value := r.Header.Get("Authorization")

		return "Authorization", value, value != ""
	},
	SecuritySchemeCookie: func(r *http.Request) (string, string, bool) {
		cookie, err := r.Cookie("JSESSIONID")

		if err != nil {
			return "", "", false
		}

		return cookie.Name, cookie.Value, true
	},
}

type SecuritySchemas interface {
	SecuritySchemeApiKeyAuth(r *http.Request, scheme SecurityScheme, name string, value string) error
	SecuritySchemeBasic(r *http.Request, scheme SecurityScheme, name string, value string) error
	SecuritySchemeBearer(r *http.Request, scheme SecurityScheme, name string, value string) error
	SecuritySchemeCookie(r *http.Request, scheme SecurityScheme, name string, value string) error
}

type SecurityCheckResult struct {
	Scheme SecurityScheme
	Value  string
}
