// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package arraytest

import (
	"encoding/json"
	"errors"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

var (
	errFieldIDIsRequiredButWasNullOrMissing                  = errors.New("field 'ID' is required but was null or missing")
	errFieldRequiredIntArrayIsRequiredButWasNullOrMissing    = errors.New("field 'RequiredIntArray' is required but was null or missing")
	errFieldRequiredStringArrayIsRequiredButWasNullOrMissing = errors.New("field 'RequiredStringArray' is required but was null or missing")
	errServiceReturnedANilResponse                           = errors.New("service returned a nil response")
)

type arrayTestRequest struct {
	EmptyAllowedArray   []string       `json:"emptyAllowedArray"`
	ObjectArray         []NestedObject `json:"objectArray"`
	OptionalStringArray []string       `json:"optionalStringArray"`
	RequiredIntArray    *[]int         `json:"requiredIntArray"`
	RequiredStringArray *[]string      `json:"requiredStringArray"`
}

type ArrayTestRequest struct {
	EmptyAllowedArray   []string       `json:"emptyAllowedArray"`
	ObjectArray         []NestedObject `json:"objectArray"`
	OptionalStringArray []string       `json:"optionalStringArray"`
	RequiredIntArray    []int          `json:"requiredIntArray"`
	RequiredStringArray []string       `json:"requiredStringArray"`
}

func (body *ArrayTestRequest) UnmarshalJSON(data []byte) error {
	var value arrayTestRequest
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.EmptyAllowedArray = value.EmptyAllowedArray
	body.ObjectArray = value.ObjectArray
	body.OptionalStringArray = value.OptionalStringArray

	if value.RequiredIntArray == nil {
		return errFieldRequiredIntArrayIsRequiredButWasNullOrMissing
	}

	body.RequiredIntArray = *value.RequiredIntArray

	if value.RequiredStringArray == nil {
		return errFieldRequiredStringArrayIsRequiredButWasNullOrMissing
	}

	body.RequiredStringArray = *value.RequiredStringArray

	return nil
}
func (body ArrayTestRequest) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.EmptyAllowedArray, validation.Length(0, 3)),
		validation.Field(&body.OptionalStringArray, validation.Length(0, 5)),
		validation.Field(&body.RequiredIntArray, validation.Required, validation.Length(2, 0)),
		validation.Field(&body.RequiredStringArray, validation.Required, validation.Length(1, 10)))
}

type nestedObject struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type NestedObject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (body *NestedObject) UnmarshalJSON(data []byte) error {
	var value nestedObject
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.Name = value.Name

	if value.ID == nil {
		return errFieldIDIsRequiredButWasNullOrMissing
	}

	body.ID = *value.ID

	return nil
}
func (body NestedObject) Validate() error {
	return nil
}
