// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package generic

import (
	"encoding/json"
	"fmt"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

type createWidgetRequest struct {
	Name *string `json:"name"`
}

type CreateWidgetRequest struct {
	Name string `json:"name"`
}

func (body *CreateWidgetRequest) UnmarshalJSON(data []byte) error {
	var value createWidgetRequest
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Name == nil {
		return fmt.Errorf("name is required")
	}

	body.Name = *value.Name

	return nil
}
func (body CreateWidgetRequest) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.Name, validation.Required, validation.RuneLength(1, 100)))
}

type errorBody struct {
	Code    *string `json:"code"`
	Message *string `json:"message"`
}

type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (body *ErrorBody) UnmarshalJSON(data []byte) error {
	var value errorBody
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Code == nil {
		return fmt.Errorf("code is required")
	}

	body.Code = *value.Code

	if value.Message == nil {
		return fmt.Errorf("message is required")
	}

	body.Message = *value.Message

	return nil
}
func (body ErrorBody) Validate() error {
	return nil
}

type widget struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type Widget struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (body *Widget) UnmarshalJSON(data []byte) error {
	var value widget
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.ID == nil {
		return fmt.Errorf("id is required")
	}

	body.ID = *value.ID

	if value.Name == nil {
		return fmt.Errorf("name is required")
	}

	body.Name = *value.Name

	return nil
}
func (body Widget) Validate() error {
	return nil
}
