// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package generic

import (
	"encoding/json"
	"errors"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

var (
	errFailedPassingSecurityChecks               = errors.New("failed passing security checks")
	errFieldCodeIsRequiredButWasNullOrMissing    = errors.New("field 'Code' is required but was null or missing")
	errFieldIDIsRequiredButWasNullOrMissing      = errors.New("field 'ID' is required but was null or missing")
	errFieldMessageIsRequiredButWasNullOrMissing = errors.New("field 'Message' is required but was null or missing")
	errFieldNameIsRequiredButWasNullOrMissing    = errors.New("field 'Name' is required but was null or missing")
	errServiceReturnedANilResponse               = errors.New("service returned a nil response")
)

type createWidgetRequest struct {
	Name *string `json:"name"`
}

type CreateWidgetRequest struct {
	Name string `json:"name"`
}

func (body *CreateWidgetRequest) UnmarshalJSON(data []byte) error {
	var value createWidgetRequest
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Name == nil {
		return errFieldNameIsRequiredButWasNullOrMissing
	}

	body.Name = *value.Name

	return nil
}
func (body CreateWidgetRequest) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.Name, validation.Required, validation.RuneLength(1, 100)))
}

type errorBody struct {
	Code    *string `json:"code"`
	Message *string `json:"message"`
}

type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (body *ErrorBody) UnmarshalJSON(data []byte) error {
	var value errorBody
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Code == nil {
		return errFieldCodeIsRequiredButWasNullOrMissing
	}

	body.Code = *value.Code

	if value.Message == nil {
		return errFieldMessageIsRequiredButWasNullOrMissing
	}

	body.Message = *value.Message

	return nil
}
func (body ErrorBody) Validate() error {
	return nil
}

type widget struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type Widget struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (body *Widget) UnmarshalJSON(data []byte) error {
	var value widget
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.ID == nil {
		return errFieldIDIsRequiredButWasNullOrMissing
	}

	body.ID = *value.ID

	if value.Name == nil {
		return errFieldNameIsRequiredButWasNullOrMissing
	}

	body.Name = *value.Name

	return nil
}
func (body Widget) Validate() error {
	return nil
}
