// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package generic

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	chi "github.com/go-chi/chi/v5"
	"net/http"
	"strings"
)

type Hooks struct {
	RequestSecurityParseFailed    func(*http.Request, string, RequestProcessingResult)
	RequestSecurityParseCompleted func(*http.Request, string)
	RequestSecurityCheckFailed    func(*http.Request, string, string, RequestProcessingResult)
	RequestSecurityCheckCompleted func(*http.Request, string, string)
	RequestBodyUnmarshalFailed    func(*http.Request, string, RequestProcessingResult)
	RequestHeaderParseFailed      func(*http.Request, string, string, RequestProcessingResult)
	RequestPathParseFailed        func(*http.Request, string, string, RequestProcessingResult)
	RequestQueryParseFailed       func(*http.Request, string, string, RequestProcessingResult)
	RequestBodyValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestHeaderValidationFailed func(*http.Request, string, RequestProcessingResult)
	RequestPathValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestQueryValidationFailed  func(*http.Request, string, RequestProcessingResult)
	RequestBodyUnmarshalCompleted func(*http.Request, string)
	RequestHeaderParseCompleted   func(*http.Request, string)
	RequestPathParseCompleted     func(*http.Request, string)
	RequestQueryParseCompleted    func(*http.Request, string)
	RequestParseCompleted         func(*http.Request, string)
	RequestProcessingCompleted    func(*http.Request, string)
	RequestRedirectStarted        func(*http.Request, string, string)
	ResponseBodyMarshalCompleted  func(*http.Request, string)
	ResponseBodyWriteCompleted    func(*http.Request, string, int)
	ResponseBodyMarshalFailed     func(http.ResponseWriter, *http.Request, string, error)
	ResponseBodyWriteFailed       func(*http.Request, string, int, error)
	ServiceCompleted              func(*http.Request, string)
}

func ensureHooks(h *Hooks) *Hooks {
	if h == nil {
		h = &Hooks{}
	}
	if h.RequestSecurityParseFailed == nil {
		h.RequestSecurityParseFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityParseCompleted == nil {
		h.RequestSecurityParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestSecurityCheckFailed == nil {
		h.RequestSecurityCheckFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityCheckCompleted == nil {
		h.RequestSecurityCheckCompleted = func(*http.Request, string, string) {}
	}
	if h.RequestBodyUnmarshalFailed == nil {
		h.RequestBodyUnmarshalFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderParseFailed == nil {
		h.RequestHeaderParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestPathParseFailed == nil {
		h.RequestPathParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestQueryParseFailed == nil {
		h.RequestQueryParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestBodyValidationFailed == nil {
		h.RequestBodyValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderValidationFailed == nil {
		h.RequestHeaderValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestPathValidationFailed == nil {
		h.RequestPathValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestQueryValidationFailed == nil {
		h.RequestQueryValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestBodyUnmarshalCompleted == nil {
		h.RequestBodyUnmarshalCompleted = func(*http.Request, string) {}
	}
	if h.RequestHeaderParseCompleted == nil {
		h.RequestHeaderParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestPathParseCompleted == nil {
		h.RequestPathParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestQueryParseCompleted == nil {
		h.RequestQueryParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestParseCompleted == nil {
		h.RequestParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestProcessingCompleted == nil {
		h.RequestProcessingCompleted = func(*http.Request, string) {}
	}
	if h.RequestRedirectStarted == nil {
		h.RequestRedirectStarted = func(*http.Request, string, string) {}
	}
	if h.ResponseBodyMarshalCompleted == nil {
		h.ResponseBodyMarshalCompleted = func(*http.Request, string) {}
	}
	if h.ResponseBodyWriteCompleted == nil {
		h.ResponseBodyWriteCompleted = func(*http.Request, string, int) {}
	}
	if h.ResponseBodyMarshalFailed == nil {
		h.ResponseBodyMarshalFailed = func(http.ResponseWriter, *http.Request, string, error) {}
	}
	if h.ResponseBodyWriteFailed == nil {
		h.ResponseBodyWriteFailed = func(*http.Request, string, int, error) {}
	}
	if h.ServiceCompleted == nil {
		h.ServiceCompleted = func(*http.Request, string) {}
	}
	return h
}

func extractSecurity(
	r *http.Request,
	hooks *Hooks,
	name string,
	requirements [][]securityProcessor,
	skipCheck bool,
) (results map[SecurityScheme]string, passed bool, checkErr error) {
	if skipCheck {
		for _, processors := range requirements {
			for _, processor := range processors {
				_, value, isExtracted := processor.extract(r)
				if !isExtracted {
					continue
				}
				if results == nil {
					results = map[SecurityScheme]string{}
				}
				results[processor.scheme] = value
			}
			break
		}
		return results, true, nil
	}

	for _, processors := range requirements {
		linkedChecksValid := true
		attemptCheckErr := error(nil)
		for _, processor := range processors {
			schemeName, value, isExtracted := processor.extract(r)
			if !isExtracted {
				linkedChecksValid = false
				break
			}
			if err := processor.handle(r, processor.scheme, schemeName, value); err != nil {
				hooks.RequestSecurityCheckFailed(r, name, string(processor.scheme),
					RequestProcessingResult{error: err, typee: SecurityCheckFailed})
				linkedChecksValid = false
				attemptCheckErr = err
				break
			}
			hooks.RequestSecurityCheckCompleted(r, name, string(processor.scheme))
			if results == nil {
				results = map[SecurityScheme]string{}
			}
			results[processor.scheme] = value
		}
		if linkedChecksValid {
			return results, true, nil
		}
		checkErr = attemptCheckErr
	}
	return results, false, checkErr
}

type requestProcessingResultType uint8

const (
	ParseSucceed requestProcessingResultType = iota
	BodyUnmarshalFailed
	BodyValidationFailed
	HeaderParseFailed
	HeaderValidationFailed
	QueryParseFailed
	QueryValidationFailed
	PathParseFailed
	PathValidationFailed
	SecurityParseFailed
	SecurityCheckFailed
)

type RequestProcessingResult struct {
	error error
	typee requestProcessingResultType
}

func NewRequestProcessingResult(t requestProcessingResultType, err error) RequestProcessingResult {
	return RequestProcessingResult{
		error: err,
		typee: t,
	}
}

func (r RequestProcessingResult) Type() requestProcessingResultType {
	return r.typee
}

func (r RequestProcessingResult) Err() error {
	return r.error
}

func WidgetsHandler(impl WidgetsService, r chi.Router, hooks *Hooks, securitySchemas SecuritySchemas) http.Handler {
	hooks = ensureHooks(hooks)

	router := &widgetsRouter{router: r, service: impl, hooks: hooks}

	router.securityHandlers = map[SecurityScheme]securityProcessor{
		SecuritySchemeBearer: {
			scheme:  SecuritySchemeBearer,
			extract: securityExtractorsFuncs[SecuritySchemeBearer],
			handle:  securitySchemas.SecuritySchemeBearer,
		},
	}

	router.getWidgetsSecureSecurityReqs = [][]securityProcessor{{router.securityHandlers[SecuritySchemeBearer]}}

	router.mount()

	return router.router
}

type widgetsRouter struct {
	router                       chi.Router
	service                      WidgetsService
	hooks                        *Hooks
	securityHandlers             map[SecurityScheme]securityProcessor
	getWidgetsSecureSecurityReqs [][]securityProcessor
}

func (router *widgetsRouter) mount() {
	router.router.Post("/classic-widgets", router.PostClassicWidgets)
	router.router.Post("/widgets", router.PostWidgets)
	router.router.Get("/widgets/echo", router.GetWidgetsEcho)
	router.router.Get("/widgets/multi", router.GetWidgetsMulti)
	router.router.Get("/widgets/redirect", router.GetWidgetsRedirect)
	router.router.Get("/widgets/secure", router.GetWidgetsSecure)
}

func (router *widgetsRouter) parsePostClassicWidgetsRequest(r *http.Request) (request PostClassicWidgetsRequest) {
	var (
		body      CreateWidgetRequest
		decodeErr error
	)
	decodeErr = json.NewDecoder(r.Body).Decode(&body)
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		router.hooks.RequestBodyUnmarshalFailed(r, "PostClassicWidgets", request.ProcessingResult)

		return
	}

	request.Body = body

	router.hooks.RequestBodyUnmarshalCompleted(r, "PostClassicWidgets")

	if err := request.Body.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: BodyValidationFailed}
		router.hooks.RequestBodyValidationFailed(r, "PostClassicWidgets", request.ProcessingResult)

		return
	}

	router.hooks.RequestParseCompleted(r, "PostClassicWidgets")

	return
}

func (router *widgetsRouter) PostClassicWidgets(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PostClassicWidgets(r.Context(), router.parsePostClassicWidgetsRequest(r))
	respond(w, r, router.hooks, "PostClassicWidgets", result.inner(), true)
}

func (router *widgetsRouter) parsePostWidgetsRequest(r *http.Request) (request PostWidgetsRequest) {
	var (
		body      CreateWidgetRequest
		decodeErr error
	)
	decodeErr = json.NewDecoder(r.Body).Decode(&body)
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		router.hooks.RequestBodyUnmarshalFailed(r, "PostWidgets", request.ProcessingResult)

		return
	}

	request.Body = body

	router.hooks.RequestBodyUnmarshalCompleted(r, "PostWidgets")

	if err := request.Body.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: BodyValidationFailed}
		router.hooks.RequestBodyValidationFailed(r, "PostWidgets", request.ProcessingResult)

		return
	}

	router.hooks.RequestParseCompleted(r, "PostWidgets")

	return
}

func (router *widgetsRouter) PostWidgets(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.PostWidgets(r.Context(), router.parsePostWidgetsRequest(r))
	respond(w, r, router.hooks, "PostWidgets", &result.response, true)
}

func (router *widgetsRouter) parseGetWidgetsEchoRequest(r *http.Request) (request GetWidgetsEchoRequest) {
	router.hooks.RequestParseCompleted(r, "GetWidgetsEcho")

	return
}

func (router *widgetsRouter) GetWidgetsEcho(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetWidgetsEcho(r.Context(), router.parseGetWidgetsEchoRequest(r))
	respond(w, r, router.hooks, "GetWidgetsEcho", &result.response, true)
}

func (router *widgetsRouter) parseGetWidgetsMultiRequest(r *http.Request) (request GetWidgetsMultiRequest) {
	router.hooks.RequestParseCompleted(r, "GetWidgetsMulti")

	return
}

func (router *widgetsRouter) GetWidgetsMulti(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetWidgetsMulti(r.Context(), router.parseGetWidgetsMultiRequest(r))
	respond(w, r, router.hooks, "GetWidgetsMulti", &result.response, true)
}

func (router *widgetsRouter) parseGetWidgetsRedirectRequest(r *http.Request) (request GetWidgetsRedirectRequest) {
	router.hooks.RequestParseCompleted(r, "GetWidgetsRedirect")

	return
}

func (router *widgetsRouter) GetWidgetsRedirect(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetWidgetsRedirect(r.Context(), router.parseGetWidgetsRedirectRequest(r))
	respond(w, r, router.hooks, "GetWidgetsRedirect", &result.response, true)
}

func (router *widgetsRouter) parseGetWidgetsSecureRequest(r *http.Request) (request GetWidgetsSecureRequest) {

	results, passed, checkErr := extractSecurity(r, router.hooks, "GetWidgetsSecure", router.getWidgetsSecureSecurityReqs, false)
	request.SecurityCheckResults = results
	if !passed {
		if checkErr != nil {
			request.ProcessingResult = RequestProcessingResult{error: checkErr, typee: SecurityCheckFailed}
			return
		}
		request.ProcessingResult = RequestProcessingResult{error: errFailedPassingSecurityChecks, typee: SecurityParseFailed}
		router.hooks.RequestSecurityParseFailed(r, "GetWidgetsSecure", request.ProcessingResult)
		return
	}
	router.hooks.RequestSecurityParseCompleted(r, "GetWidgetsSecure")

	router.hooks.RequestParseCompleted(r, "GetWidgetsSecure")

	return
}

func (router *widgetsRouter) GetWidgetsSecure(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetWidgetsSecure(r.Context(), router.parseGetWidgetsSecureRequest(r))
	respond(w, r, router.hooks, "GetWidgetsSecure", &result.response, true)
}

type response struct {
	statusCode  int
	body        interface{}
	bodyRaw     []byte
	contentType string
	redirectURL string
	headers     map[string]string
	cookies     []http.Cookie
}

type responseInterface interface {
	inner() *response
}

var (
	_ = xml.Marshal
	_ = json.Marshal
	_ = errors.New
	_ = fmt.Sprint
)

func respond(w http.ResponseWriter, r *http.Request, hooks *Hooks, name string, resp *response, hasContent bool) {
	for header, value := range resp.headers {
		w.Header().Set(header, value)
	}

	cookies := resp.cookies
	for i := range cookies {
		http.SetCookie(w, &cookies[i])
	}

	if url := resp.redirectURL; url != "" {
		switch resp.statusCode {
		case 301, 302, 303, 307, 308:
			hooks.RequestRedirectStarted(r, name, url)
			http.Redirect(w, r, url, resp.statusCode)
			hooks.ServiceCompleted(r, name)
			return
		}
	}

	hooks.RequestProcessingCompleted(r, name)

	if !hasContent {
		w.WriteHeader(resp.statusCode)
		hooks.ServiceCompleted(r, name)
		return
	}

	// Marshal BEFORE writing the status code so a serialization failure can
	// still surface as a clean 500 instead of a 2xx with a truncated body —
	// once WriteHeader fires, headers/status are committed to the wire and
	// we can no longer signal the error to the client.
	var body []byte
	if resp.body != nil {
		var err error
		switch resp.contentType {
		case "application/xml":
			body, err = xml.Marshal(resp.body)
		case "application/octet-stream":
			var ok bool
			if body, ok = (resp.body).([]byte); !ok {
				err = errors.New("body is not []byte")
			}
		case "text/html":
			body = []byte(fmt.Sprint(resp.body))
		case "application/json":
			fallthrough
		default:
			body, err = json.Marshal(resp.body)
		}
		if err != nil {
			hooks.ResponseBodyMarshalFailed(w, r, name, err)
			http.Error(w, "internal server error", http.StatusInternalServerError)
			return
		}
		hooks.ResponseBodyMarshalCompleted(r, name)
	} else if len(resp.bodyRaw) > 0 {
		body = resp.bodyRaw
	}

	if ct := resp.contentType; ct != "" {
		w.Header().Set("Content-Type", ct)
	}
	w.WriteHeader(resp.statusCode)

	if len(body) > 0 {
		count, err := w.Write(body)
		if err != nil {
			hooks.ResponseBodyWriteFailed(r, name, count, err)
			return
		}
		hooks.ResponseBodyWriteCompleted(r, name, count)
	}

	hooks.ServiceCompleted(r, name)
}

type PostClassicWidgetsResponse interface {
	responseInterface
	postClassicWidgetsResponse()
}

type postClassicWidgetsResponse struct {
	response
}

func (*postClassicWidgetsResponse) postClassicWidgetsResponse() {}

func (r *postClassicWidgetsResponse) inner() *response {
	return &r.response
}

type postClassicWidgetsStatusCodeResponseBuilder struct {
	response
}

func PostClassicWidgetsResponseBuilder() *postClassicWidgetsStatusCodeResponseBuilder {
	return new(postClassicWidgetsStatusCodeResponseBuilder)
}

func (builder *postClassicWidgetsStatusCodeResponseBuilder) StatusCode200() *postClassicWidgets200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &postClassicWidgets200ContentTypeBuilder{response: builder.response}
}

type postClassicWidgets200ContentTypeBuilder struct {
	response
}

type PostClassicWidgets200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostClassicWidgets200ApplicationJsonResponseBuilder) Build() PostClassicWidgetsResponse {
	return &postClassicWidgetsResponse{response: builder.response}
}

func (builder *postClassicWidgets200ContentTypeBuilder) ApplicationJson() *postClassicWidgets200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postClassicWidgets200ApplicationJsonBodyBuilder{response: builder.response}
}

type postClassicWidgets200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postClassicWidgets200ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostClassicWidgets200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostClassicWidgets200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets200ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostClassicWidgets200ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostClassicWidgets200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets200ApplicationJsonBodyBuilder) Body(body Widget) *PostClassicWidgets200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostClassicWidgets200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgetsStatusCodeResponseBuilder) StatusCode400() *postClassicWidgets400ContentTypeBuilder {
	builder.response.statusCode = 400

	return &postClassicWidgets400ContentTypeBuilder{response: builder.response}
}

type postClassicWidgets400ContentTypeBuilder struct {
	response
}

type PostClassicWidgets400ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostClassicWidgets400ApplicationJsonResponseBuilder) Build() PostClassicWidgetsResponse {
	return &postClassicWidgetsResponse{response: builder.response}
}

func (builder *postClassicWidgets400ContentTypeBuilder) ApplicationJson() *postClassicWidgets400ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postClassicWidgets400ApplicationJsonBodyBuilder{response: builder.response}
}

type postClassicWidgets400ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postClassicWidgets400ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostClassicWidgets400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostClassicWidgets400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets400ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostClassicWidgets400ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostClassicWidgets400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets400ApplicationJsonBodyBuilder) Body(body ErrorBody) *PostClassicWidgets400ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostClassicWidgets400ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgetsStatusCodeResponseBuilder) StatusCode500() *postClassicWidgets500ContentTypeBuilder {
	builder.response.statusCode = 500

	return &postClassicWidgets500ContentTypeBuilder{response: builder.response}
}

type postClassicWidgets500ContentTypeBuilder struct {
	response
}

type PostClassicWidgets500ApplicationJsonResponseBuilder struct {
	response
}

func (builder *PostClassicWidgets500ApplicationJsonResponseBuilder) Build() PostClassicWidgetsResponse {
	return &postClassicWidgetsResponse{response: builder.response}
}

func (builder *postClassicWidgets500ContentTypeBuilder) ApplicationJson() *postClassicWidgets500ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &postClassicWidgets500ApplicationJsonBodyBuilder{response: builder.response}
}

type postClassicWidgets500ApplicationJsonBodyBuilder struct {
	response
}

func (builder *postClassicWidgets500ApplicationJsonBodyBuilder) BodyBytesWithEncoding(encoding string, body []byte) *PostClassicWidgets500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body
	if builder.response.headers == nil {
		builder.response.headers = make(map[string]string)
	}
	builder.response.headers["Content-Encoding"] = encoding

	return &PostClassicWidgets500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets500ApplicationJsonBodyBuilder) BodyBytes(body []byte) *PostClassicWidgets500ApplicationJsonResponseBuilder {
	builder.response.bodyRaw = body

	return &PostClassicWidgets500ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *postClassicWidgets500ApplicationJsonBodyBuilder) Body(body ErrorBody) *PostClassicWidgets500ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &PostClassicWidgets500ApplicationJsonResponseBuilder{response: builder.response}
}

type WidgetsService interface {
	PostClassicWidgets(context.Context, PostClassicWidgetsRequest) PostClassicWidgetsResponse
	PostWidgets(context.Context, PostWidgetsRequest) *Response[Widget]
	GetWidgetsEcho(context.Context, GetWidgetsEchoRequest) *Response[Widget]
	GetWidgetsMulti(context.Context, GetWidgetsMultiRequest) *Response[Widget]
	GetWidgetsRedirect(context.Context, GetWidgetsRedirectRequest) *Response[any]
	GetWidgetsSecure(context.Context, GetWidgetsSecureRequest) *Response[Widget]
}

type PostClassicWidgetsRequest struct {
	Body             CreateWidgetRequest
	ProcessingResult RequestProcessingResult
}

type PostWidgetsRequest struct {
	Body CreateWidgetRequest
	RequestMeta
}

func (r PostWidgetsRequest) GetHeader() any {
	return nil
}

type GetWidgetsEchoRequest struct {
	RequestMeta
}

func (r GetWidgetsEchoRequest) GetHeader() any {
	return nil
}

type GetWidgetsMultiRequest struct {
	RequestMeta
}

func (r GetWidgetsMultiRequest) GetHeader() any {
	return nil
}

type GetWidgetsRedirectRequest struct {
	RequestMeta
}

func (r GetWidgetsRedirectRequest) GetHeader() any {
	return nil
}

type GetWidgetsSecureRequest struct {
	RequestMeta
}

func (r GetWidgetsSecureRequest) GetHeader() any {
	return nil
}

type RequestMeta struct {
	ProcessingResult     RequestProcessingResult
	SecurityCheckResults map[SecurityScheme]string
}

func (r RequestMeta) GetProcessingResult() RequestProcessingResult {
	return r.ProcessingResult
}

func (r RequestMeta) GetSecurityCheckResults() map[SecurityScheme]string {
	return r.SecurityCheckResults
}

// Request is implemented by every generated XxxRequest whose operation is
// marked with x-go-generics. GetProcessingResult and GetSecurityCheckResults
// are promoted from the embedded RequestMeta; GetHeader is emitted per
// operation because the Header type is unique per endpoint.
type Request interface {
	GetProcessingResult() RequestProcessingResult
	GetSecurityCheckResults() map[SecurityScheme]string
	GetHeader() any
}

type Response[B any] struct {
	response
}

type ResponseBuilder[B any] struct {
	response
}

// NewResponse creates a builder for a Response[B]. Content-type defaults to
// "application/json"; override with ContentType() if needed.
func NewResponse[B any]() *ResponseBuilder[B] {
	return &ResponseBuilder[B]{response: response{contentType: "application/json"}}
}

func (b *ResponseBuilder[B]) Status(code int) *ResponseBuilder[B] {
	b.response.statusCode = code
	return b
}

func (b *ResponseBuilder[B]) ContentType(ct string) *ResponseBuilder[B] {
	b.response.contentType = ct
	return b
}

// Typed content-type shortcuts. Equivalent to ContentType("application/json")
// etc. but read more naturally in fluent chains. Add more as needed.
func (b *ResponseBuilder[B]) ApplicationJson() *ResponseBuilder[B] {
	b.response.contentType = "application/json"
	return b
}

func (b *ResponseBuilder[B]) ApplicationXml() *ResponseBuilder[B] {
	b.response.contentType = "application/xml"
	return b
}

func (b *ResponseBuilder[B]) ApplicationOctetStream() *ResponseBuilder[B] {
	b.response.contentType = "application/octet-stream"
	return b
}

func (b *ResponseBuilder[B]) ApplicationFormUrlencoded() *ResponseBuilder[B] {
	b.response.contentType = "application/x-www-form-urlencoded"
	return b
}

func (b *ResponseBuilder[B]) TextPlain() *ResponseBuilder[B] {
	b.response.contentType = "text/plain"
	return b
}

func (b *ResponseBuilder[B]) TextHtml() *ResponseBuilder[B] {
	b.response.contentType = "text/html"
	return b
}

func (b *ResponseBuilder[B]) TextCsv() *ResponseBuilder[B] {
	b.response.contentType = "text/csv"
	return b
}

func (b *ResponseBuilder[B]) Body(body B) *ResponseBuilder[B] {
	b.response.body = body
	return b
}

func (b *ResponseBuilder[B]) BodyAny(body any) *ResponseBuilder[B] {
	b.response.body = body
	return b
}

func (b *ResponseBuilder[B]) BodyRaw(raw []byte) *ResponseBuilder[B] {
	b.response.bodyRaw = raw
	return b
}

func (b *ResponseBuilder[B]) Header(key, value string) *ResponseBuilder[B] {
	if b.response.headers == nil {
		b.response.headers = map[string]string{}
	}
	b.response.headers[key] = value
	return b
}

func (b *ResponseBuilder[B]) Cookie(c http.Cookie) *ResponseBuilder[B] {
	b.response.cookies = append(b.response.cookies, c)
	return b
}

func (b *ResponseBuilder[B]) Redirect(url string) *ResponseBuilder[B] {
	b.response.redirectURL = url
	return b
}

func (b *ResponseBuilder[B]) Build() *Response[B] {
	return &Response[B]{response: b.response}
}

type SecurityScheme string

const (
	SecuritySchemeBearer SecurityScheme = "Bearer"
)

type securityProcessor struct {
	scheme  SecurityScheme
	extract func(r *http.Request) (string, string, bool)
	handle  func(r *http.Request, scheme SecurityScheme, name string, value string) error
}

var securityExtractorsFuncs = map[SecurityScheme]func(r *http.Request) (string, string, bool){
	SecuritySchemeBearer: func(r *http.Request) (string, string, bool) {
		value := r.Header.Get("Authorization")

		if !strings.HasPrefix(value, "Bearer ") {
			return "", "", false
		}

		value = value[7:]

		return "", value, value != ""
	},
}

type SecuritySchemas interface {
	SecuritySchemeBearer(r *http.Request, scheme SecurityScheme, name string, value string) error
}

type SecurityCheckResult struct {
	Scheme SecurityScheme
	Value  string
}
