// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package minimal

import "errors"

var (
	errServiceReturnedANilResponse = errors.New("service returned a nil response")
)

type TestArray = []string
