// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package minimal

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	chi "github.com/go-chi/chi/v5"
	"net/http"
	"reflect"
)

// Hooks are observability callbacks fired by the generated routing layer.
// Any field may be left nil — ensureHooks() at handler-init time fills the
// nil entries with no-op stubs, so call sites never need to nil-check.
//
// Contract: hooks are for observability (logging, metrics, tracing). The
// runtime owns the response. ResponseBodyMarshalFailed receives an
// http.ResponseWriter for inspection only — the runtime calls http.Error
// immediately after the hook returns, so writing to w from the hook will
// produce a duplicate-WriteHeader warning. Read headers/r.Context() at most.
type Hooks struct {
	RequestSecurityParseFailed    func(*http.Request, string, RequestProcessingResult)
	RequestSecurityParseCompleted func(*http.Request, string)
	RequestSecurityCheckFailed    func(*http.Request, string, string, RequestProcessingResult)
	RequestSecurityCheckCompleted func(*http.Request, string, string)
	RequestBodyUnmarshalFailed    func(*http.Request, string, RequestProcessingResult)
	RequestHeaderParseFailed      func(*http.Request, string, string, RequestProcessingResult)
	RequestPathParseFailed        func(*http.Request, string, string, RequestProcessingResult)
	RequestQueryParseFailed       func(*http.Request, string, string, RequestProcessingResult)
	RequestBodyValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestHeaderValidationFailed func(*http.Request, string, RequestProcessingResult)
	RequestPathValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestQueryValidationFailed  func(*http.Request, string, RequestProcessingResult)
	RequestBodyUnmarshalCompleted func(*http.Request, string)
	RequestHeaderParseCompleted   func(*http.Request, string)
	RequestPathParseCompleted     func(*http.Request, string)
	RequestQueryParseCompleted    func(*http.Request, string)
	RequestParseCompleted         func(*http.Request, string)
	RequestProcessingCompleted    func(*http.Request, string)
	RequestRedirectStarted        func(*http.Request, string, string)
	ResponseBodyMarshalCompleted  func(*http.Request, string)
	ResponseBodyWriteCompleted    func(*http.Request, string, int)
	ResponseBodyMarshalFailed     func(http.ResponseWriter, *http.Request, string, error)
	ResponseBodyWriteFailed       func(*http.Request, string, int, error)
	ServiceCompleted              func(*http.Request, string)
}

func ensureHooks(h *Hooks) *Hooks {
	if h == nil {
		h = &Hooks{}
	}
	if h.RequestSecurityParseFailed == nil {
		h.RequestSecurityParseFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityParseCompleted == nil {
		h.RequestSecurityParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestSecurityCheckFailed == nil {
		h.RequestSecurityCheckFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestSecurityCheckCompleted == nil {
		h.RequestSecurityCheckCompleted = func(*http.Request, string, string) {}
	}
	if h.RequestBodyUnmarshalFailed == nil {
		h.RequestBodyUnmarshalFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderParseFailed == nil {
		h.RequestHeaderParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestPathParseFailed == nil {
		h.RequestPathParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestQueryParseFailed == nil {
		h.RequestQueryParseFailed = func(*http.Request, string, string, RequestProcessingResult) {}
	}
	if h.RequestBodyValidationFailed == nil {
		h.RequestBodyValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestHeaderValidationFailed == nil {
		h.RequestHeaderValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestPathValidationFailed == nil {
		h.RequestPathValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestQueryValidationFailed == nil {
		h.RequestQueryValidationFailed = func(*http.Request, string, RequestProcessingResult) {}
	}
	if h.RequestBodyUnmarshalCompleted == nil {
		h.RequestBodyUnmarshalCompleted = func(*http.Request, string) {}
	}
	if h.RequestHeaderParseCompleted == nil {
		h.RequestHeaderParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestPathParseCompleted == nil {
		h.RequestPathParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestQueryParseCompleted == nil {
		h.RequestQueryParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestParseCompleted == nil {
		h.RequestParseCompleted = func(*http.Request, string) {}
	}
	if h.RequestProcessingCompleted == nil {
		h.RequestProcessingCompleted = func(*http.Request, string) {}
	}
	if h.RequestRedirectStarted == nil {
		h.RequestRedirectStarted = func(*http.Request, string, string) {}
	}
	if h.ResponseBodyMarshalCompleted == nil {
		h.ResponseBodyMarshalCompleted = func(*http.Request, string) {}
	}
	if h.ResponseBodyWriteCompleted == nil {
		h.ResponseBodyWriteCompleted = func(*http.Request, string, int) {}
	}
	if h.ResponseBodyMarshalFailed == nil {
		h.ResponseBodyMarshalFailed = func(http.ResponseWriter, *http.Request, string, error) {}
	}
	if h.ResponseBodyWriteFailed == nil {
		h.ResponseBodyWriteFailed = func(*http.Request, string, int, error) {}
	}
	if h.ServiceCompleted == nil {
		h.ServiceCompleted = func(*http.Request, string) {}
	}
	return h
}

func extractSecurity(
	r *http.Request,
	hooks *Hooks,
	name string,
	requirements [][]securityProcessor,
	skipCheck bool,
) (results map[SecurityScheme]string, passed bool, checkErr error) {
	if skipCheck {
		// Expose every extractable credential across all OR-branches so the
		// handler can decide. Validation is skipped by contract.
		for _, processors := range requirements {
			for _, processor := range processors {
				_, value, isExtracted := processor.extract(r)
				if !isExtracted {
					continue
				}
				if results == nil {
					results = map[SecurityScheme]string{}
				}
				results[processor.scheme] = value
			}
		}
		return results, true, nil
	}

	for _, processors := range requirements {
		// Per-branch buffer: a partially-extracted branch must not leak its
		// credentials into the final results.
		branchResults := map[SecurityScheme]string{}
		linkedChecksValid := true
		attemptCheckErr := error(nil)
		for _, processor := range processors {
			schemeName, value, isExtracted := processor.extract(r)
			if !isExtracted {
				linkedChecksValid = false
				break
			}
			if err := processor.handle(r, processor.scheme, schemeName, value); err != nil {
				hooks.RequestSecurityCheckFailed(r, name, string(processor.scheme),
					RequestProcessingResult{error: err, typee: SecurityCheckFailed})
				linkedChecksValid = false
				attemptCheckErr = err
				break
			}
			hooks.RequestSecurityCheckCompleted(r, name, string(processor.scheme))
			branchResults[processor.scheme] = value
		}
		if linkedChecksValid {
			if len(branchResults) > 0 {
				results = branchResults
			}
			return results, true, nil
		}
		// Preserve the first real handle() error across OR-branches. A later
		// branch that fails only on extract (attemptCheckErr stays nil) must
		// NOT overwrite a real auth-handler error from an earlier branch.
		if checkErr == nil {
			checkErr = attemptCheckErr
		}
	}
	return results, false, checkErr
}

type requestProcessingResultType uint8

const (
	ParseSucceed requestProcessingResultType = iota
	BodyUnmarshalFailed
	BodyValidationFailed
	HeaderParseFailed
	HeaderValidationFailed
	QueryParseFailed
	QueryValidationFailed
	PathParseFailed
	PathValidationFailed
	SecurityParseFailed
	SecurityCheckFailed
)

type RequestProcessingResult struct {
	error error
	typee requestProcessingResultType
}

func NewRequestProcessingResult(t requestProcessingResultType, err error) RequestProcessingResult {
	return RequestProcessingResult{
		error: err,
		typee: t,
	}
}

func (r RequestProcessingResult) Type() requestProcessingResultType {
	return r.typee
}

func (r RequestProcessingResult) Err() error {
	return r.error
}

var (
	_ = reflect.ValueOf
)

func isNilResponse(v responseInterface) bool {
	if v == nil {
		return true
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Pointer, reflect.Interface, reflect.Chan, reflect.Func, reflect.Map, reflect.Slice:
		return rv.IsNil()
	}
	return false
}

func DefaultHandler(impl DefaultService, r chi.Router, hooks *Hooks) http.Handler {
	hooks = ensureHooks(hooks)

	router := &defaultRouter{router: r, service: impl, hooks: hooks}

	router.mount()

	return router.router
}

type defaultRouter struct {
	router  chi.Router
	service DefaultService
	hooks   *Hooks
}

func (router *defaultRouter) mount() {
	router.router.Get("/test", router.GetTest)
}

func (router *defaultRouter) parseGetTestRequest(r *http.Request) (request GetTestRequest) {
	router.hooks.RequestParseCompleted(r, "GetTest")

	return
}

func (router *defaultRouter) GetTest(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	result := router.service.GetTest(r.Context(), router.parseGetTestRequest(r))
	if isNilResponse(result) {
		router.hooks.ResponseBodyMarshalFailed(w, r, "GetTest", errServiceReturnedANilResponse)
		http.Error(w, "internal server error", http.StatusInternalServerError)
		return
	}
	respond(w, r, router.hooks, "GetTest", result.inner(), false)
}

type response struct {
	statusCode  int
	body        interface{}
	bodyRaw     []byte
	contentType string
	redirectURL string
	headers     map[string]string
	cookies     []http.Cookie
}

type responseInterface interface {
	inner() *response
}

var (
	_ = xml.Marshal
	_ = json.Marshal
	_ = errors.New
	_ = fmt.Sprint
	_ = reflect.ValueOf
)

func respond(w http.ResponseWriter, r *http.Request, hooks *Hooks, name string, resp *response, hasContent bool) {
	for header, value := range resp.headers {
		w.Header().Set(header, value)
	}

	cookies := resp.cookies
	for i := range cookies {
		http.SetCookie(w, &cookies[i])
	}

	if url := resp.redirectURL; url != "" {
		switch resp.statusCode {
		case 301, 302, 303, 307, 308:
			hooks.RequestRedirectStarted(r, name, url)
			http.Redirect(w, r, url, resp.statusCode)
			hooks.ServiceCompleted(r, name)
			return
		}
	}

	hooks.RequestProcessingCompleted(r, name)

	if !hasContent {
		w.WriteHeader(resp.statusCode)
		hooks.ServiceCompleted(r, name)
		return
	}

	// Marshal BEFORE writing the status code so a serialization failure can
	// still surface as a clean 500 instead of a 2xx with a truncated body —
	// once WriteHeader fires, headers/status are committed to the wire and
	// we can no longer signal the error to the client.
	var body []byte
	if resp.body != nil {
		var err error
		switch resp.contentType {
		case "application/xml":
			body, err = xml.Marshal(resp.body)
		case "application/octet-stream":
			// Fast path for []byte and its aliases (e.g. type X = []byte).
			// Fall back to reflect for named types whose underlying type is
			// []byte (type X []byte) — the plain type assertion above would
			// fail those since Go checks type identity, not underlying type.
			if b, ok := (resp.body).([]byte); ok {
				body = b
			} else {
				rv := reflect.ValueOf(resp.body)
				if rv.Kind() == reflect.Slice && rv.Type().Elem().Kind() == reflect.Uint8 {
					body = rv.Bytes()
				} else {
					err = errors.New("body is not []byte")
				}
			}
		case "text/html":
			body = []byte(fmt.Sprint(resp.body))
		case "application/json":
			fallthrough
		default:
			body, err = json.Marshal(resp.body)
		}
		if err != nil {
			hooks.ResponseBodyMarshalFailed(w, r, name, err)
			http.Error(w, "internal server error", http.StatusInternalServerError)
			return
		}
		hooks.ResponseBodyMarshalCompleted(r, name)
	} else if len(resp.bodyRaw) > 0 {
		body = resp.bodyRaw
	}

	if ct := resp.contentType; ct != "" {
		w.Header().Set("Content-Type", ct)
	}
	w.WriteHeader(resp.statusCode)

	if len(body) > 0 {
		count, err := w.Write(body)
		if err != nil {
			hooks.ResponseBodyWriteFailed(r, name, count, err)
			return
		}
		hooks.ResponseBodyWriteCompleted(r, name, count)
	}

	hooks.ServiceCompleted(r, name)
}

type GetTestResponse interface {
	responseInterface
	getTestResponse()
}

type getTestResponse struct {
	response
}

func (*getTestResponse) getTestResponse() {}

func (r *getTestResponse) inner() *response {
	return &r.response
}

type getTestStatusCodeResponseBuilder struct {
	response
}

func GetTestResponseBuilder() *getTestStatusCodeResponseBuilder {
	return new(getTestStatusCodeResponseBuilder)
}

func (builder *getTestStatusCodeResponseBuilder) StatusCode200() *GetTest200ResponseBuilder {
	builder.response.statusCode = 200

	return &GetTest200ResponseBuilder{response: builder.response}
}

type GetTest200ResponseBuilder struct {
	response
}

func (builder *GetTest200ResponseBuilder) Build() GetTestResponse {
	return &getTestResponse{response: builder.response}
}

type DefaultService interface {
	GetTest(context.Context, GetTestRequest) GetTestResponse
}

type GetTestRequest struct {
	ProcessingResult RequestProcessingResult
}

type SecurityScheme string

const ()

type securityProcessor struct {
	scheme  SecurityScheme
	extract func(r *http.Request) (string, string, bool)
	handle  func(r *http.Request, scheme SecurityScheme, name string, value string) error
}

var securityExtractorsFuncs = map[SecurityScheme]func(r *http.Request) (string, string, bool){}

type SecuritySchemas interface{}

type SecurityCheckResult struct {
	Scheme SecurityScheme
	Value  string
}
