// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package simplearray

import (
	"encoding/json"
	"errors"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

var (
	errServiceReturnedANilResponse = errors.New("service returned a nil response")
)

type simpleArrayTest struct {
	OptionalArray []string `json:"optionalArray"`
}

type SimpleArrayTest struct {
	OptionalArray []string `json:"optionalArray"`
}

func (body *SimpleArrayTest) UnmarshalJSON(data []byte) error {
	var value simpleArrayTest
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.OptionalArray = value.OptionalArray

	return nil
}
func (body SimpleArrayTest) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.OptionalArray, validation.Length(1, 5)))
}
